export { default as Home } from "./Home"
export { default as Pag1 } from "./Pag1"
export { default as Pag2 } from "./Pag2"
export { default as Pag3 } from "./Pag3"
export { default as Pag4 } from "./Pag4"
export { default as CadastroMensal} from "./CadastroMensal"
export { default as CadastroAnual} from "./CadastroAnual"
export { default as Entrar } from "./Login"